import type { Task } from './types'

export const getSeedData = (): Task[] => {
  const now = new Date()
  const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000)
  const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000)
  const nextWeek = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000)
  const lastWeek = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)

  return [
    {
      id: 'seed-1',
      title: 'Design new landing page',
      description: 'Create a modern, responsive landing page for the product launch. Include hero section, features, pricing, and testimonials.',
      status: 'in-progress',
      priority: 'high',
      category: 'work',
      tags: ['design', 'frontend', 'urgent'],
      dueDate: tomorrow,
      startDate: yesterday,
      assignedTo: 'Sarah Chen',
      estimatedHours: 16,
      completionPercentage: 45,
      createdAt: lastWeek,
      updatedAt: now,
      comments: [
        {
          id: 'comment-1',
          taskId: 'seed-1',
          userId: '1',
          userName: 'John Doe',
          content: 'Looking great! Can we make the hero section more prominent?',
          createdAt: yesterday,
        },
        {
          id: 'comment-2',
          taskId: 'seed-1',
          userId: '2',
          userName: 'Sarah Chen',
          content: 'Sure, I\'ll increase the hero height and add a subtle animation.',
          createdAt: now,
        },
      ],
      attachments: [
        {
          id: 'attach-1',
          name: 'landing-mockup.fig',
          url: '#',
          type: 'application/figma',
          size: 2048000,
          uploadedAt: yesterday,
          uploadedBy: 'Sarah Chen',
        },
      ],
      checklist: [],
      subtasks: [
        {
          id: 'sub-1',
          title: 'Create wireframes',
          status: 'done',
          createdAt: lastWeek,
          completedAt: yesterday,
        },
        {
          id: 'sub-2',
          title: 'Design hero section',
          status: 'done',
          createdAt: lastWeek,
          completedAt: yesterday,
        },
        {
          id: 'sub-3',
          title: 'Design features section',
          status: 'in-progress',
          createdAt: yesterday,
        },
        {
          id: 'sub-4',
          title: 'Design pricing section',
          status: 'todo',
          createdAt: yesterday,
        },
      ],
      customFields: {},
      blockedBy: [],
    },
    {
      id: 'seed-2',
      title: 'Implement authentication system',
      description: 'Set up JWT-based authentication with OAuth integration for Google and GitHub.',
      status: 'todo',
      priority: 'urgent',
      category: 'work',
      tags: ['backend', 'security', 'authentication'],
      dueDate: tomorrow,
      startDate: undefined,
      assignedTo: 'Mike Johnson',
      estimatedHours: 24,
      completionPercentage: 0,
      createdAt: yesterday,
      updatedAt: yesterday,
      comments: [],
      attachments: [],
      checklist: [],
      subtasks: [
        {
          id: 'sub-5',
          title: 'Set up JWT library',
          status: 'todo',
          createdAt: yesterday,
        },
        {
          id: 'sub-6',
          title: 'Create OAuth endpoints',
          status: 'todo',
          createdAt: yesterday,
        },
        {
          id: 'sub-7',
          title: 'Implement token refresh',
          status: 'todo',
          createdAt: yesterday,
        },
      ],
      customFields: {},
      blockedBy: [],
    },
    {
      id: 'seed-3',
      title: 'Weekly team sync',
      description: 'Discuss project progress, blockers, and plan for next sprint.',
      status: 'done',
      priority: 'medium',
      category: 'work',
      tags: ['meeting', 'team'],
      dueDate: yesterday,
      startDate: yesterday,
      assignedTo: 'Team',
      estimatedHours: 1,
      completionPercentage: 100,
      createdAt: lastWeek,
      updatedAt: yesterday,
      completedAt: yesterday,
      comments: [
        {
          id: 'comment-3',
          taskId: 'seed-3',
          userId: '3',
          userName: 'Team Lead',
          content: 'Great progress everyone! Keep up the momentum.',
          createdAt: yesterday,
        },
      ],
      attachments: [],
      checklist: [],
      subtasks: [],
      customFields: {},
      blockedBy: [],
    },
    {
      id: 'seed-4',
      title: 'Update API documentation',
      description: 'Document all new endpoints and update existing ones with examples.',
      status: 'review',
      priority: 'medium',
      category: 'work',
      tags: ['documentation', 'api'],
      dueDate: nextWeek,
      startDate: lastWeek,
      assignedTo: 'Alex Rodriguez',
      estimatedHours: 8,
      completionPercentage: 85,
      createdAt: lastWeek,
      updatedAt: now,
      comments: [],
      attachments: [],
      checklist: [],
      subtasks: [
        {
          id: 'sub-8',
          title: 'Document authentication endpoints',
          status: 'done',
          createdAt: lastWeek,
          completedAt: yesterday,
        },
        {
          id: 'sub-9',
          title: 'Document user endpoints',
          status: 'done',
          createdAt: lastWeek,
          completedAt: yesterday,
        },
        {
          id: 'sub-10',
          title: 'Add code examples',
          status: 'in-progress',
          createdAt: yesterday,
        },
      ],
      customFields: {},
      blockedBy: [],
    },
    {
      id: 'seed-5',
      title: 'Morning workout routine',
      description: '30-minute cardio and strength training session.',
      status: 'done',
      priority: 'low',
      category: 'health',
      tags: ['fitness', 'daily'],
      dueDate: now,
      startDate: now,
      assignedTo: 'Personal',
      estimatedHours: 0.5,
      completionPercentage: 100,
      createdAt: lastWeek,
      updatedAt: now,
      completedAt: now,
      comments: [],
      attachments: [],
      checklist: [],
      subtasks: [],
      customFields: {},
      blockedBy: [],
    },
    {
      id: 'seed-6',
      title: 'Learn TypeScript advanced patterns',
      description: 'Study generics, conditional types, and utility types in depth.',
      status: 'in-progress',
      priority: 'medium',
      category: 'learning',
      tags: ['typescript', 'programming', 'self-study'],
      dueDate: nextWeek,
      startDate: lastWeek,
      assignedTo: 'Personal',
      estimatedHours: 10,
      completionPercentage: 60,
      createdAt: lastWeek,
      updatedAt: now,
      comments: [],
      attachments: [],
      checklist: [],
      subtasks: [
        {
          id: 'sub-11',
          title: 'Complete generics tutorial',
          status: 'done',
          createdAt: lastWeek,
          completedAt: yesterday,
        },
        {
          id: 'sub-12',
          title: 'Study conditional types',
          status: 'done',
          createdAt: lastWeek,
          completedAt: yesterday,
        },
        {
          id: 'sub-13',
          title: 'Practice utility types',
          status: 'in-progress',
          createdAt: yesterday,
        },
        {
          id: 'sub-14',
          title: 'Build sample project',
          status: 'todo',
          createdAt: yesterday,
        },
      ],
      customFields: {},
      blockedBy: [],
    },
    {
      id: 'seed-7',
      title: 'Fix critical production bug',
      description: 'Users reporting 500 errors on checkout page. Investigate and fix ASAP.',
      status: 'blocked',
      priority: 'urgent',
      category: 'work',
      tags: ['bug', 'critical', 'production'],
      dueDate: now,
      startDate: yesterday,
      assignedTo: 'DevOps Team',
      estimatedHours: 4,
      completionPercentage: 20,
      createdAt: yesterday,
      updatedAt: now,
      comments: [
        {
          id: 'comment-4',
          taskId: 'seed-7',
          userId: '4',
          userName: 'DevOps',
          content: 'Blocked by database migration. Need DBA approval.',
          createdAt: now,
        },
      ],
      attachments: [],
      checklist: [],
      subtasks: [],
      customFields: {},
      blockedBy: ['database-migration-approval'],
    },
    {
      id: 'seed-8',
      title: 'Prepare quarterly presentation',
      description: 'Create slides showcasing Q4 achievements and Q1 goals.',
      status: 'todo',
      priority: 'high',
      category: 'work',
      tags: ['presentation', 'management'],
      dueDate: nextWeek,
      startDate: undefined,
      assignedTo: 'Management Team',
      estimatedHours: 6,
      completionPercentage: 0,
      createdAt: yesterday,
      updatedAt: yesterday,
      comments: [],
      attachments: [],
      checklist: [],
      subtasks: [],
      customFields: {},
      blockedBy: [],
    },
    {
      id: 'seed-9',
      title: 'Grocery shopping',
      description: 'Buy ingredients for meal prep this week.',
      status: 'todo',
      priority: 'low',
      category: 'personal',
      tags: ['errands', 'shopping'],
      dueDate: tomorrow,
      startDate: undefined,
      assignedTo: 'Personal',
      estimatedHours: 1,
      completionPercentage: 0,
      createdAt: now,
      updatedAt: now,
      comments: [],
      attachments: [],
      checklist: [],
      subtasks: [],
      customFields: {},
      blockedBy: [],
    },
    {
      id: 'seed-10',
      title: 'Code review for PR #234',
      description: 'Review the new dashboard component implementation.',
      status: 'in-progress',
      priority: 'high',
      category: 'work',
      tags: ['code-review', 'frontend'],
      dueDate: now,
      startDate: now,
      assignedTo: 'Sarah Chen',
      estimatedHours: 2,
      completionPercentage: 50,
      createdAt: now,
      updatedAt: now,
      comments: [
        {
          id: 'comment-5',
          taskId: 'seed-10',
          userId: '2',
          userName: 'Sarah Chen',
          content: 'Looks good overall, just some minor styling suggestions.',
          createdAt: now,
        },
      ],
      attachments: [],
      checklist: [],
      subtasks: [],
      customFields: {},
      blockedBy: [],
    },
  ]
}

export const shouldLoadSeedData = (): boolean => {
  try {
    const data = localStorage.getItem('taskflow-pro-data')
    if (!data) return true

    const parsed = JSON.parse(data)
    // Load seed data if tasks don't exist or array is empty
    return !parsed.tasks || !Array.isArray(parsed.tasks) || parsed.tasks.length === 0
  } catch {
    return true
  }
}

// Helper to force reload seed data (for development/testing)
export const clearAndLoadSeedData = (): void => {
  localStorage.removeItem('taskflow-pro-data')
  console.log('Cleared localStorage. Reload page to load seed data.')
}
